[workspace]

members = ["packages/*", "contracts/*"]

[workspace.package]
edition = "2021"
homepage = "https://paystreams.finance"

[workspace.metadata]
description = "PayStreams Finance"

[workspace.dependencies]
cosmwasm-std = { version = "0.16.2" }
cosmwasm-storage = { version = "0.16.0" }
cw-storage-plus = "0.8.0"
cw2 = "0.8.1"
schemars = "0.8.3"
serde = { version = "1.0.127", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.26" }

[workspace.dev-dependencies]
cosmwasm-schema = { version = "0.16.0" }
