[workspace]

members = ["packages/*", "contracts/*"]

[workspace.package]
edition = "2021"
homepage = "https://paystreams.finance"

[workspace.metadata]
description = "PayStreams Finance"

[workspace.dependencies]
cosmwasm-std = { version = "1.3" }
cosmwasm-storage = { version = "1.0.1" }
cw-storage-plus = "1.0.1"
cw2 = "1.0.1"
schemars = "0.8.3"
serde = { version = "1.0.127", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.26" }
cw-utils = { version = "1.0.1" }
white-whale = { git = "https://github.com/White-Whale-Defi-Platform/white-whale-core"}

[workspace.dev-dependencies]
cosmwasm-schema = { version = "1.3" }
cw-multi-test = { version = "0.16.5" }